name: Build Play Store Release App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Signed Production AAB
        env:
          SIGNING_PASS: ${{ secrets.RELEASE_PASSWORD }}
        run: |
          cordova platform add android
          cordova build android --release -- --keystore=ekideakey.p12 --storePassword=$SIGNING_PASS --alias=ekideakey --password=$SIGNING_PASS --packageType=bundle

      - name: Upload Store Ready AAB
        uses: actions/upload-artifact@v4
        with:
          name: EKIDEA-PlayStore-Release
          path: platforms/android/app/build/outputs/bundle/release/*.aab
